FROM python:3.8-slim

WORKDIR /app

# Copy only the necessary files first
COPY requirements.txt .

# Install dependencies
RUN pip install -r requirements.txt

# Copy the entire project
COPY . .

# Expose the port your Flask app runs on
EXPOSE 8080

# Run the Flask application
CMD ["python", "app.py"]