stages:
  data_ingestion:
    cmd: python -m src.chicken_disease_classification.pipeline.stage_01_data_ingestion
    deps:
     - src/chicken_disease_classification/pipeline/stage_01_data_ingestion.py
     - config/config.yaml
    outs:
     - artifacts/data_ingestion/Chicken-fecal-images

  prepare_base_model:
    cmd: python -m src.chicken_disease_classification.pipeline.stage_02_base_model_preperation
    deps:
     - src/chicken_disease_classification/pipeline/stage_02_base_model_preperation.py
     - config/config.yaml
    params:
     - prepare_base_model.IMAGE_SIZE
     - prepare_base_model.WEIGHTS
     - prepare_base_model.INCLUDE_TOP
     - prepare_base_model.CLASSES
     - prepare_base_model.LEARNING_RATE
    outs:
     - artifacts/prepare_base_model

  training:
    cmd: python -m src.chicken_disease_classification.pipeline.stage_04_training
    deps:
     - src/chicken_disease_classification/pipeline/stage_04_training.py
     - src/chicken_disease_classification/components/prepare_callback.py
     - config/config.yaml
     - artifacts/data_ingestion/Chicken-fecal-images
     - artifacts/prepare_base_model
    params:
     - training.EPOCHS
     - training.BATCH_SIZE
     - training.AUGMENTATION
     - prepare_base_model.IMAGE_SIZE
    outs:
     - artifacts/training/model.h5

  model_evaluation:
    cmd: python -m src.chicken_disease_classification.pipeline.stage_05_model_evaluation
    deps:
     - src/chicken_disease_classification/pipeline/stage_05_model_evaluation.py
     - config/config.yaml
     - artifacts/training/model.h5
     - artifacts/data_ingestion/Chicken-fecal-images
    params:
     - prepare_base_model.IMAGE_SIZE
     - training.BATCH_SIZE
    metrics:
    - score.json:
        cache: false
